name: tugasmobxbangundatar
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobx: ^2.0.0
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7  # Updated version
  mobx_codegen: ^2.0.3  # Updated version

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
